---
# © 2024 marcSerrano2613
# Licensed under the MIT License. See LICENSE file in the project root for full license information.

# Metadata of permissions_on_passwd.yml
systems:
  - name: "Ubuntu"
    versions: ['24.04', '23.10', '22.04', '20.04']
    
  - name: "Fedora"
    versions: ['40']
    
description: "The /etc/passwd file contains user account information that is used by many system 
utilities and therefore must be readable for these utilities to operate."
     
rationale: "It is critical to ensure that the /etc/passwd file is protected from unauthorized write
access. Although it is protected by default, the file permissions could be changed either
inadvertently or through malicious actions."
     
cvss_score: 5.0
