---
# © 2024 marcSerrano2613
# Licensed under the MIT License. See LICENSE file in the project root for full license information.

- name: Ensure xz versions 5.6.0 or 5.6.1 are not installed
  hosts: localhost
  tasks:
     - name: Include OS-specific variables
       include_vars: "../vars/Fedora.yml"
       
     - name: Include global variables
       include_vars: "../../common/vars/global_vars.yml"
     
     - name: Check if xz is installed
       include_tasks: ../../common/tasks/check_packages_versions.yml
       vars:
          package_name: "{{ xz_package }}"
          remediation: "{{ install_xz_command }}"
          versions_xz_vulnerable: "{{ versions_xz }}"
       register: package_check_result
    
