---
# © 2024 marcSerrano2613
# Licensed under the MIT License. See LICENSE file in the project root for full license information.

- name: Ensure Avahi Server is not installed
  hosts: localhost
  vars:
     remediation_commands:
        - systemctl stop avahi-daemon.service
        - systemctl stop avahi-daemon.socket
        - apt purge avahi-daemon

  tasks:
     - name: Include OS-specific variables
       include_vars: "../vars/{{ ansible_facts.distribution }}.yml"

     - name: Check if avahi-daemon is not installed
       include_tasks: ../../common/tasks/check_if_package_installed.yml
       vars:
          package_name: "{{ avahi_daemon_package }}"
          remediation: "{{ remediation_commands }}"
