---
# © 2024 marcSerrano2613
# Licensed under the MIT License. See LICENSE file in the project root for full license information.

- name: Ensure sudo is installed
  hosts: localhost
  tasks:
     - name: Include OS-specific variables
       include_vars: "../../common/vars/global_vars.yml"

     - name: Check if sudo is installed
       include_tasks: ../../common/tasks/check_if_package_not_installed.yml
       vars:
          package_name: "{{ sudo_package }}"
          remediation: apt install
       register: package_check_result
