---
# © 2024 marcSerrano2613
# Licensed under the MIT License. See LICENSE file in the project root for full license information.

- name: Gather package facts
  ansible.builtin.package_facts:
     manager: auto
        
- name: Check if package is installed
  ansible.builtin.fail:
    msg: "Package {{ package_name }} is installed. [Remediation] {{ remediation }}"
  when: package_name in ansible_facts.packages
